[connections.snowflake]
account = "psb54603.us-east-1"
user = "Admin"
password = "Triggo@2024"
role = "accountadmin"
warehouse = "COMPUTE_WH"
database = "CC_QUICKSTART_CORTEX_DOCS"
schema = "DATA"
client_session_keep_alive = true